### ISSUE TITLE
[resto druid] Implement Checklist

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#1040]
Creating this issue to brainstorm checklist ideas for Resto Druid.

I'm on vacation until 12/28 and probably won't be able to actually work on it until then, but I'd like to at least gather some ideas.

**Comment by kfinch** [comment]
Possible skeleton:

Always Be Casting
   - Healing Uptime
   - Absolute Uptime
Spell Uptimes (??)
   - Lifebloom Uptime
   - Efflo Uptime
Use your Little Cooldowns
   - Swiftmend cast effic
   - WG cast ratio (??)
   - CW cast effic
   - Flourish cast effic
Use your Big Cooldowns
   - EoG cast effic
   - Tranq cast effic
Something Something Mana Usage (??)
   ???
Be Prepared
   - Food
   - Flask
   - Rune
   - Potions
   - Enchants
   - Legendaries upgraded

**Comment by David-EU** [comment]
About Mana usage it could be usefull to see how mana was saved by relics that improve mana regeneration or from clear casting.
What I don't like much also is WoWAnalyzer telling it did bad job because I missed some swiftmen, flourish, efflo or tranqu. Here I disagree with the facts they must be casted on cd, healing is only situational and so must be used at the right moment instead of asap, particulary when you don't need.

**Comment by MartijnHols** [comment]
The cast efficiency thresholds set for most healing spells are pretty forgiving, missing 20%+ casts is quite a lot and I feel like the amount of that is easy to underestimate. Having said that, their thresholds might have to be re-evaluated to see if they're still proper.

We look primarily at the performance of the selected player, if he wants to improve it using the suggested spells more often will help so long as it's not overhealing. When healing trivial content or bringing too many healers (and/or really good healers), you'll find more instances where it might overheal and that would be a good reason to take these specific suggestions a little less serious, but in general when doing challenging content it's important to pay attention to those kinds of things.

Sadly we can't tell how much raid damage is going out or how much healing your other healers are doing so we can't take that into account.

Spells like Tranq are very efficient and will save you and your healing team a lot of mana if cast regularly.

**Comment by David-EU** [comment]
What you say is also correct, but as long you're not overhealing ;)
So yeah if the raid is not full hp they must be casted on CD, on challenging fight it can be mostly everytime ;)
But for example sometimes there is some damage breaks in fights, when you just do near nothing, or I can just ask another healer (with many mana) to push a little the heal so I can relax and regen and restart healing when there is heave damage. That is really bad for active time and for cd casts, but it should be considered as a part of our gameplay, healing is mana management vs having efficient hps, I see a lot of healers casting everything they can and then run oom and cause a wipe. And that for WoWAnalyzer is a good performance because they will have very good hps and no mana at the end of the fight, which is mainly the cause of the wipe xD
That's why I said healing is heavily situational and performance evaluation should not be raw hps troughput. I think the rule also apply to tank who need to use they defensives cooldowns when they take heave damage and not "stupidly" asap.
With warcraftlogs, you know everything, who are healers, what they cast, when they cast, what are damage, who take damage, when, etc. I don't see a technical reason where it is not feasable. 
But well I agree this wont make your life easier... it will be much complicated and take more significant time than a basic hps ranking. But I expect this new healing evaluation algorithm could be used as well for every healers ;)
I just have the idea where there is two fight modes, one where the damage are hight/constant (like overall raid hp < 90%) and one where the healers are relaxed and where dont need to cast every cd. The second mode could be used to mitigate the bad evaluation of their gameplay.
This problem could be or not depending the class and specialisation gameplay, but so far as resto druid I dont play like WoWAnalyzer is telling me, and still have a nice overall hps comparing to other healers with similar ilvl, I talk to my mates regulary and they are statisfied with what I do, and for sure I keep them alive which is the final goal :)
