### ISSUE TITLE
Add a Mitigation/Defensive Cooldowns Tracker

### ISSUE THREAD

**Issue by FaideWW** [WoWAnalyzer/WoWAnalyzer#1083]
Effective mitigation usage is a key piece of data missing from tank analysis currently.  

What I'd like this module to capture is the following:

- Defensive abilities and passives and their DR values/affected damage schools (maybe this can be an extension of `Abilities`).  Somehow this should also count for absorbs like Ignore Pain and various trinkets with absorb effects.
- Incoming damage taken and calculation of pre-mitigation damage intake
- A breakdown of the contribution of individual casts of a defensive ability/passive (how much damage did spell X mitigate?)
- Detection of irregular damage spikes and whether they were properly defended against

I'm planning on implementing this myself; opening this issue to track progress and elicit feedback/suggestions from others on how they'd go about this or other things they'd like to see tracked.

**Comment by FaideWW** [comment]
How I see "damage prevented per spell" working:

Maintain a list of passive DR effects (things like Thick Hide for guardian) and active DR spells (e.g. Barkskin for guardian).  

When a damage taken event occurs, record all the contributing DR effects that were present.  Use the DR formula `damageAfterMitigation = damageBeforeMitigation * (1 - totalDR%)` to obtain the raw damage value, and by extension the total amount of damage mitigated.

Each DR effect contributed a portion of the total reduction.  Determine the percentage of overall contribution for every DR effect, and distribute the amount of damage mitigated according to those percentages.  This is the "amount mitigated" of each DR effect for this particular damage event.

For example:
Thick hide is a 6% DR, Barkskin is a 20% DR. Together they provide 24.8% total DR.

A damage taken event occurs for 300k post-mitigation.  The raw damage value is `300k / (1 - 0.248) ~= 399k`.

Thick hide contributed 23% of the total DR (`6 / sum of DRs`), meaning it mitigated ~92k damage.
Barkskin contributed 77% of the total DR (`20 / sum of DRs`), meaning it mitigated ~307k damage.

**Comment by yajinni** [comment]
This would be awesome for my blood dk: http://www.wowhead.com/spell=48792/icebound-fortitude
If possible i would like to add this to the cooldown tracker tab.

**Comment by FaideWW** [comment]
In 8.0 the WCL event API will include "unmitigated damage taken" as a field on damage events, greatly simplifying this feature. I am going to put this on hold until then.  If someone else would like to pick this up for 7.3.5, feel free to do so.

**Comment by MartijnHols** [comment]
We have a BFA [branch](https://github.com/WoWAnalyzer/WoWAnalyzer/tree/bfa) and [subdomain](https://bfa.wowanalyzer.com) (with full CI) up that this could be contributed to. It might be challenging to find raid logs, but dungeon logs should give a good idea of how stuff will look like or you could do an old raid just for the logs.

**Comment by Gebuz** [comment]
I'm gonna start working on implementing damage mitigation next week. Hopefully I'll be able to get something useful finished before BFA release (where I'm gonna spent most of my free time grinding rep >.<). I'm not sure how readable this is, but I figured I might aswell post it here anyway:
https://github.com/Gebuz/WoWAnalyzer/projects/3

Basically using the same formula explained by Faide above, contribute dmg mitigated between different abilities and display dmg mitigated by each ability over the encounter. Expanding on that in the future I think being able to see the breakdown by either ability or damage source would also be a cool feature.

**Comment by MartijnHols** [comment]
About the DR formula proposed here; Everything on the site currently uses the single DR formula; `actual damage taken / (100% - DR percentage) * DR percentage` = damage reduced. This gives a considerably lower value than what's proposed here, but it was picked on purpose not because of a lack of an alternative. We need consistent numbers; we can't begin showing conflicting data in different modules. Have you given any thought to this?

**Comment by Gebuz** [comment]
I planned to include basically every Damage reduction in the game (or atleast from class abilities, armor/vers and raid boss abilities). I assume other Damage reduction effects would need to be updated to account for this. The problematic ones would be the externals (ironbark, barrier, devotion aura, etc.) I haven't looked at how these are being done but I'd assume we could extend it to also do the samething when calculating those.

Other problematic things to consider are: Devotion Aura, Last Defender where the damage reduction depends on number of allies/enemies nearby. Also percentage absorbs (Will of the necropolis, Sacrifice, Soullink) that are effectively also just percent damage mitigation counted as healing done are a bit problematic. It's possible to include them in the calculation (that's a simple math problem) but I'm not sure how feasible that is since some are also included in healing done, while others simultaniously does damage to another target (sacrifice/soullink).

**Comment by MartijnHols** [comment]
I've actually been working on an explanation for the DR analysis for Devotion Aura where I explain why I picked the formula I mentioned. I wouldn't really want to change it much as I think it's the right approach when analyzing a DR like Devo. I'll share it when it's done to show what I mean.

**Comment by Gebuz** [comment]
I understand that calculating it like that makes a lot of sense for the paladin, since other damage reduction will often be out of your control, so assuming Devo is the only optional one (should I have been using sac/mercy instead?) is reasonable.

However when tracking all mitigation I don't think that approach would work, as there will (atleast for tanks) be a lot more mitigations you can choose to use or not to use. Maybe it would make sense to display both values? The low value you calculate for comparing it to the other talents where we assume all other damage reduction is final, and the higher value where we assume all damage reduction is optional (idk the right word for that, basically assume any of the other dmg mitigation is just as likely to be turned off as devo aura).

Or maybe it's fine to only show your formula for it along with an explanation as to why that method was chosen over the other one for that specific case.

**Comment by MartijnHols** [comment]
Both seems like a good solution. An alternative would be a combination where we assign modifiers to special DRs so that for example Armor gets a 100% share based on the DR it provided while something optional or timeable like Devo gets 0%, but that could get messy when you have two of those DRs up at the same time, so showing both might indeed be best. 👍

**Comment by MartijnHols** [comment]
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/Parser/Paladin/Holy/Modules/Talents/DevotionAuraDamageReduction.md#devotion-aura-damage-reduction-analysis

**Comment by Gebuz** [comment]
If anybody wants to help out I would appreciate a whitelist of all BFA raid (and dungeon) abilities that are considered "AOE damage" for the purpose of avoidance (and feint) as discussed here: #1184. If you can't test it (in the case of the raid abilities) it's cool if you just guess for now, we can update it once we have done the encounters. No need to do the Legion abilities since they are going away soon.
