### ISSUE TITLE
[BUG] Tearstone of Elune triggered ~25 times, only one was caught.

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#1160]
https://wowanalyzer.com/report/yWB68j2PqaZkpKMV/42/53

**Comment by kfinch** [comment]
I have a framework update that I will PR soon that includes an update to Tearstone, running the update it sees 20 procs. Can you tell me where you got the number 25 from?

**Comment by buimichael** [comment]
@kfinch 
I was using this for cross reference: https://rubensayshi.github.io/wcl-rdruid-mastery/#/mastery-analyzer/result?reportID=yWB68j2PqaZkpKMV&fightID=42&actorID=53

After investigating WCL further:
Amount of rejuf buffs applied is 196. 4 PotA proccs and 135 rejuv casts.
This leaves 196-8-135 = 53 "magic" rejuvs. Seems a little much?

https://www.warcraftlogs.com/reports/yWB68j2PqaZkpKMV/#fight=42&type=auras&pins=3%240%240%24Off%24%23244F4B%24auras-gained%24-1%240.0.0.Any%24138582676.0.0.Druid%24true%240.0.0.Any%24true%24774%241&target=53

**Comment by kfinch** [comment]
Ok, I looked closer at this log.

The 135 casts is consistent everywhere I looked. When looking at applications however, I see where it says 196 for Rejuv in WCL, yet also in WCL once I chose the option to show events, I see only 167 events where Rejuvenation was applied or refreshed... I'm not sure what to make of this. Next, I looked at the developer's events tab in WoWA, and I see 177 applied or refreshes. This is consistent with the 167 from WCL because 10 of the applications were fabricated prepull events.

This leaves 32 rejuvs unaccounted for by hardcasting (because prepull rejuvs won't have a cast event in the logs). 8 of them are accounted for by PotA, leaving 24. I guess my 20 is missing a few? I'll look further into it.

**Comment by kfinch** [comment]
Oh, I think I figure it out. Player was often casting Wildgrowth -> Rejuv, and occasionally Tearstone was proccing on the same target he cast the Rejuv on. Due to the timestamps, my analyzer was attributing both of those application to hardcasts, when it fact it was one to hardcast and one to Tearstone.
