### ISSUE TITLE
[Disc Priest] March of the Legion

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#1167]
The March of the Legion proc from CoS Dungeon set [http://www.wowhead.com/item=134529/chain-of-scorched-bones&bonus=1826:1497](url) is wrong calculated atm. 

Here an example log:
[https://wowanalyzer.com/report/HFJD2WZdncahTgXm/7/18](url)
3.24 % (total) / 53k HPS 

Warcraftlogs says something different 
[https://www.warcraftlogs.com/reports/HFJD2WZdncahTgXm#fight=7&type=healing&source=18](url) 
7,82 % | 27,64 M Healing / 353,45 M (total) 

so it should be:
1,61 M Hps / 100 * 7,82 % = 125902 Hps 

Big difference and a real strong (OP) item in my opinion. 

Would be nice if someone can fix it! :)

**Comment by Pewtro** [comment]
![image](https://user-images.githubusercontent.com/29204244/35221604-0a0c065c-ff7b-11e7-8f70-57be50a53a54.png)

**Comment by MartijnHols** [comment]
![image](https://user-images.githubusercontent.com/4565223/35221606-1126b626-ff7b-11e7-9b5b-60407ce9e997.png)

I think he is referring to WCL's Atonement healing estimation. This display is only a rough estimation and often wrong. I am pretty sure our display is correct and should be used instead. Please let us know if you think otherwise and we'll re-open the issue.

**Comment by MartijnHols** [comment]
The people over at  https://discord.gg/focusedwill will know more about the accuracy of WCL's Atonement sources versus that of ours (we show it in one of the tabs), if you want more information.
