### ISSUE TITLE
[core] DeathTracker not seeing a resurrection

### ISSUE THREAD

**Issue by kfinch** [WoWAnalyzer/WoWAnalyzer#1207]
See the following log: https://wowanalyzer.com/report/q6cnmrjRYwxZV93H/8-Mythic+Felhounds+of+Sargeras+-+Kill+(4:58)/Dustbunny

Player died, was resurrected, but the DeathTracker did not catch it. There didn't appear to be a resurrect event, and in fact from the log it's not clear to me how the player was resurrected... events around the moment of death are a little weird.

**Comment by Sharrq** [comment]
It looks like they had a soulstone ... i wonder if using the soulstone doesnt count as a rez?

**Comment by Sharrq** [comment]
yea the only thing i was worried about is getting ressurected and not doing anything for a few seconds ... which is why i mentioned checking for all four of begincast, cast, healing received, damage received.

But i suppose being a couple seconds off isnt the worst scenario. i also dont know how damage received and healing received is going to work on someone that is dead, depending on how the events line up. so it might not be worth touching those 2. Begincast and cast seems resonable though.
