### ISSUE TITLE
Improvements to the timeline

### ISSUE THREAD

**Issue by yajinni** [WoWAnalyzer/WoWAnalyzer#1254]
So i was wondering if 2 things were possible. 

First something like the user can click on an ability listed to disable/filter it out of the timeline so they can focus on the spells that they want.

Second, some sort of toggle to group the spells in the timeline into one line based on thier categorization from the cast efficiency tab. Forgive my shitty ms paint example lol

https://github.com/WoWAnalyzer/WoWAnalyzer/issues/1083
![image](https://user-images.githubusercontent.com/9600587/35364367-c58d265a-013c-11e8-9f7e-c8be5815dbcd.png)

**Comment by kfinch** [comment]
Both things are definitely possible. 

User specified filtering would probably be easy, would just need some thought on how the user interface would look.

From what I remember of how the timelines are setup, it would take a little more work to get those combined timelines, but I don't think it would be all that hard to implement. Take a look in https://github.com/WoWAnalyzer/WoWAnalyzer/tree/master/src/Main/Timeline for most of the relevant code.

**Comment by Sharrq** [comment]
While whoever is working on this, I also got a suggestion from someone a while back that was asking if it was possible to show on the timeline where an error occurred. 

Using Frost Mage as an example, like highlighting or putting some kind of marker on a flurry hard cast (since you should never hard cast flurry), or putting an error marker somewhere to identify where they made a rotational mistake. 

Might be cool for showing the user exactly where they made the mistake as opposed to "you made x number of mistakes".

**Comment by Gebuz** [comment]
@Sharrq it is possible to highlight bad casts on the timeline as of #1469

**Comment by MartijnHols** [comment]
@yajinni you can determine the order yourself now as per #1487

Currently with showing cooldowns, combining rows isn't really an option. It could be with an alternative view that hides cooldowns, a PR for this would be welcome.

**Comment by MartijnHols** [comment]
@yajinni If you or anyone feels inspired you're welcome to contribute such a feature, but going to close this issue.
