### ISSUE TITLE
Add contributor pages

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1330]
Like:
https://rust.facepunch.com/team/member/garry.newman/
https://rust.facepunch.com/team/member/maurino.berry/
https://rust.facepunch.com/team/member/alex.rehberg/
https://rust.facepunch.com/team/member/minh.le/

**Comment by joshinat0r** [comment]
Started working on those pages, that's what I've come up with so far.
All those infos are from CONTRIBUTORS.js, with an option to define their own texts/lists.
Not sure if the Main/Alt part is usefull, thought it might be a nice addition.

Changelog is right now only working for core & blood, not sure if its possible to import all changelogs via regex or something like that. Otherwise I'd have to import them all manually, just some copy&paste in the end.

Would like to get some feedback on the layout or additional stuff anyone would like to see.

![contributors](https://user-images.githubusercontent.com/29842841/37989814-b9762ac6-3204-11e8-9e2e-4703887c901b.PNG)

**Comment by Gebuz** [comment]
Added in #1535, courtesy of @joshinat0r.
PS: the changelog list is awesome.
