### ISSUE TITLE
[Disc Priest] Rapture max usage

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#1352]
Hey guys =)
Got a few logs where my max pw:s usage during Rapture is higher than the max value. 
![rapture](https://user-images.githubusercontent.com/32820288/35964741-f5c8dd32-0cb8-11e8-9a86-e9de39ee6857.jpg)
https://wowanalyzer.com/report/Wzjf42a7KMq8tLNn/9-Mythic+Portal+Keeper+Hasabel+-+Kill+(8:27)/Past%C3%A0/cast-efficiency

or
![rapture2](https://user-images.githubusercontent.com/32820288/35964868-4bf8a7d2-0cb9-11e8-8425-3fc36ccc83ac.jpg)
https://wowanalyzer.com/report/k1JxtGdDrpZVaFKA/18-Heroic+Varimathras+-+Kill+(3:24)/Past%C3%A0/cast-efficiency

Hope this can help you finding the problem. =)

**Comment by Gebuz** [comment]
I'm guessing the issue is that maxCasts is manually calculated so it doesn't take temporary hastebuffs into account. Looking at how it's calculated it probably misses a few casts due to summing uptime aswell (if you have .1sec left of the buff you can cast a full PW:S but it will only be counted as .1 cast in max casts)
