### ISSUE TITLE
[Disc Priest] Penance cast efficiency

### ISSUE THREAD

**Issue by Pastaaa** [WoWAnalyzer/WoWAnalyzer#1408]
Hey Guys =)
I just noticed something went wrong at cast efficiency with penance. 
![](https://screenshotscdn.firefoxusercontent.com/images/f42c8291-dfd2-40c9-98c9-ce6a623916ce.png)

The max value of 61 casts is correct at a 9:04 long fight but the spell usage of 78 not. 
https://wowanalyzer.com/report/ry3hmBYXzdxG6Tn2/41-Mythic+Portal+Keeper+Hasabel+-+Kill+(9:04)/67-Past%C3%A0/cast-efficiency

Seems like every disc priest log got this bug. 

https://wowanalyzer.com/report/YMtRgWnc1Dr3B2kj/35-Heroic+Argus+the+Unmaker+-+Kill+(8:01)/15-Joshpriest/cast-efficiency

https://wowanalyzer.com/report/WMXcDZ9zk3nQVjqv/17-Heroic+Varimathras+-+Kill+(2:59)/145-Amanda/timeline

**Comment by Pewtro** [comment]
This is caused by each cast of penance, having 3 casts of the exact same spellID resulting in this happening. In reality you had 26 casts of Penance.
![image](https://user-images.githubusercontent.com/29204244/36369968-82d36db2-155d-11e8-81a5-a3f528013c51.png)

So as how to fix it, I am not sure - but the correct information is seen by dividing the cast amount by 3 for now 😄

**Comment by MartijnHols** [comment]
This is properly calculated in modules such as the penance bolts wasted statistic. I'm not sure what change led to the cast efficiency showing this wrong.

**Comment by karlpralow** [comment]
I'm looking into this right now

**Comment by abelito75** [comment]
I believe this was fixed
