### ISSUE TITLE
[WW] Chi spent data

### ISSUE THREAD

**Issue by tarthyn** [WoWAnalyzer/WoWAnalyzer#1501]
Hi there,

I have noticed a strange issue, maybe related to having >1 (windwalker) monk in a log parse:
check this one for example : https://wowanalyzer.com/report/8dnpKrc46zqb7B9D

My guildmate (id 5) does not have the cost reducing Fist of Fury legendary, and his Chi spent section shows them costing 2. On the opposite, I do (id 4) have them equipped on this log, but mine shows a cost of 3.

It's the first time a take a closer look at this Chi spent section, and it looks like (at least in this case) there's something wrong there!

Thanks for taking a look ;-)

**Comment by Juko8** [comment]
Yeah, i've been noticing stuff is weird with the chi tracking. Apparently it's looking at the chi cost from spell data rather than how much was actually spent. This is also causing it to think Blackout Kick has a 3 Chi cost since that's what its baseline cost is (reduced to 1 by rank 2 and 3 of the spell).

**Comment by Gebuz** [comment]
This would also be a good excuse to update the ChiTracker to use the core ResourceTracker which has support for adding resource cost reduction that isn't included in the event.

**Comment by Juko8** [comment]
I have requested changes #1502
