### ISSUE TITLE
Allow searching by region/realm/playername

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1525]
Using the parses API endpoint we could make getting started easier.

https://www.warcraftlogs.com/v1/parses/character/Zerotorescue/AlAkir/EU?api_key=x

I'm not entirely sure if that's the best for our goal; WCL also has `/rankings/character/{characterName}/{serverName}/{serverRegion}` that might be more useful.

**Comment by joshinat0r** [comment]
the majority of work for the frontend so far is done:

The general flow from the search to the overview is as following:

```
Player selects region/realm/charname
    call to blizzards-API
        when the char doesn't exist:
            alert
        when the char exists:
            save the path to the character-image in localStorage of the browser
            open the parse-overview
            fetch parses from WCL
                char doesn't exist on WCL:
                    message with link
```

the parse-overview then checks if the char exists on WCL, shows an error if the char doesn't exist at all or if the char has no parses for the selected raid tier. Checks also if the char has an entry in the localStore to display the image or makes a request to save it.

Saving the path of the image to the localStorage saves a few bnet-requests since there's no need to check again if the player exists (and the path of the image never changes for a character). 
Doing the bnet-call before the WCL one to check if a char has actually parses was done because the WCL-APIs response time can take up to 5-6 seconds (depending on the amount of parses). Not only makes the user experience smoother, but filters typing errors (or wrong region, thus saving WCL requests) and allows a more clean error message since the user is redirected to the parse-overview with reasons why the player doesn't have any parses and a link to get started with logging (instead of showing an alert).

**Stuff that's missing/not working**
- support for special-chars of our API
special chars cause issues with our API, which means parsing anything from the TW, KR, RU region or from any realm/character combo with anything beyond A-Z with is impossible to fetch right now. 
I've looked into the server folder but I have not a single idea what it's doing and what needs to be changed to support the characters without breaking anything.

- proper actorID for analyze link
not a major issue, but the parses-API doesn't include the actorID of the player for a log, just the name and the WoW-ID (the same ID thats partitially returned with the bnet-API for the char-image). But the combatants-info do not contain any of this information, just the actorID and the WCL-ID. I'm not quite sure why the actorID is in the URL since it works just fine without right now (the analyze-button submits a "+"-char instead of an actorID and does its job), but I guess its there for a reason. 

- character renames / realm transfer
not an issue on our end but on WCLs end, but the parses-API returns a name for each parse. But this name is not the name used in the log but the one you submit as parameter. Makes it impossible to get a direct match between the character and actor to analyze a player that merged a character on WCL. This will get a fix with soon (Kirha is working on the rankings already on beta), but until then we'll just open the character-overview for the fight and the user has to select the correct player. 

- caching of the bnet-API
maybe not as important, but should be considered since both encounterStats and characterParses do the same requests for the item-icons (they fetch the item-icon when we don't have it in ITEMS) possibly making the same requests several times. More or less the same for the character-pictures we're fetching for the parses-overview.

![select](https://user-images.githubusercontent.com/29842841/38663062-1378cb54-3e36-11e8-9788-06915c259d64.PNG)
![overview](https://user-images.githubusercontent.com/29842841/38663065-15fc1f0c-3e36-11e8-93b1-5222cad38399.PNG)

**Comment by Gebuz** [comment]
Looks awesome!

PS: ActorID is needed because a log can have multiple characters with the same name (cross realm hurray).

**Comment by joshinat0r** [comment]
What would be the best workaround for that?
My idea would be to check if the submitted actorID is `somethingsomething`, then check if the player-name exists in the log twice (or more times) and actorID is `somethingsomething` and then open the character-selection, let the user select manually.

We could technically somehow compare spec&gear, generate some checksum and use that as actorID. But thats still not 100% unique (and is more work 😄)

**Comment by Gebuz** [comment]
could just default to char select if two actors have the same name, it should be super rare.

**Comment by MartijnHols** [comment]
Looking good! I created issue #1580 for the duplicate player name issue, but that probably wouldn't solve it for you. Your proposed solution of sending to player selection might be best.

I do have some suggestions:
- We could add a cache for battlenet requests, and it might even be fairly simple to add on the existing WCL cache, but if it's to cache items I think it might be cleaner to store an item cache. That should also be refreshed occasionally. The battle.net API allows for like 10 requests per second iirc so I don't think we'll hit that cap any time soon, and especially not before capping out on WCL.
- I think the front page header could use some polishing, it takes a lot of space this way and doesn't really look appealing. Maybe make it tabbed? Not the optimal solution, but does make it much easier to style without taking a lot of space or being cluttered.
- I like the layout of the fight overview but since most of our users read left to right, I think we should have the fight selection left and fight list right. I don't think this changes the feel of the page much, would it?
- How about putting the refresh button somewhere near the fight list? E.g. above it in a separate row? It's kinda hard to find right now and inconsistent with other pages.
- I reckon the most common use case is going to be to get the latest report regardless of raid, difficulty or spec, so how about setting it to all specs, difficulties, raids and bosses by default?
- When swapping the fight list columns swapping the columns for spec/difficulties/raid might also make sense.
- No need to explain the player unknown situation I think. It will be fairly rare and irrelevant for most users, and it isn't a big deal to land on fight selection instead of the report page so users might not even think much of it.
- How about showing logs that were disqualified due not being logged with advanced logging enabled? This again eliminates the need for an explanation box and would better match expectations and be much clearer. Also the message is irrelevant for most users.
- How about making the fight list completely clickable with the > icon at the right side instead of the small analyze link? I think that would be more consistent with most of the rest of the layout.
- I think sorting by date by default would fit the most common use case of just wanting to get the latest report.
- There seems to be a lot of whitespace around the class icon, but that entire panel looks really nice.
- I don't really like the dropdowns for raid/boss/metric/sort by... They feel like a dated interface.

Overall this looks really good and (without knowing code quality) more than ready to be merged, the suggestions above are just perfectionistic.

**Comment by joshinat0r** [comment]
- according to [blue posts](https://us.battle.net/forums/en/bnet/topic/15255185550) the increased it to 100 calls per second, but 36.000 per hour. Shouldn't be an issue since we have the most used trinkets anyways in ITEMS. Just something we could consider.

- Not sure if having tabs would look better,I personally like the current one more. I'll try a tabbed version in the next few days.

- Changed the order from `parses -> filter` to `filter -> parses`, feel that it kinda looks akward with the char to the left. Fine with it either way.

- Refresh button is now on the top of the parses and not on the filter-pane

- The default selection is always all specs, all difficulties, DPS and ordered by date for all bosses of antorus. Was too lazy to check for most used specs & difficulties 😅 . Just unchecked a few for the screenshots to show "hey, you can uncheck those individually"

- Not quite sure what you meant with `When swapping the fight list columns swapping the columns for spec/difficulties/raid might also make sense.`, but I changed the order of the filters to spec/difficulties/raid.

- Removed the info about the player names, it'll just open the log, make an alert `It appears like another XYZ is in this log, please select the correct one` and open the character-selection for the fight. Should also work just fine when issue #1580 is done (as long as the friendlies names are not changed).

- Logs logged without advanced logging are now shown, it's just a rather empty row without talents & gear.

- complete row is now clickable and changed `analyze` to a chevron.

- as mentioned, is already filtered by date by default

- moved the class icon to the right to have less space on the left. We could also remove them entirely, the class should be pretty obvious by looking at the specs. Just added them for aesthetics.

- feel free to suggest something else 😄 I have no idea what could replace dropdowns there other than having a component thats doing the same thing just without the browser-specific render-style.

PRing this would only make sense once special-characters are supported by our API. Isn't really usefull to offer a new feature that just supports half of the EU/US servers (and then only half of those characters).

I'd add support for special-charaters on my own, but pretty new to the whole node & npm-world and would probably destory more than I add.
"Just" needs support for `parses/character/${name}/${realm}/${region}` to support `encodeURIComponent`-values for name/realm. At least that's what WCL needs, we could send something else from the app to our API and the API handles the proper encoding for WCL.

![char_parsing](https://user-images.githubusercontent.com/29842841/38780089-b9e7478e-40d1-11e8-8d23-c367defc6abc.PNG)

**Comment by joshinat0r** [comment]
I tried plain text first for the toggle, but I don't think that would sugguest that you can toggle between report or character. That's why I used the button-style with opacity slightly toned down.

![tab1](https://user-images.githubusercontent.com/29842841/38809593-4ff79ae6-4184-11e8-85cb-c0b18a7bfb6a.PNG)
![tab2](https://user-images.githubusercontent.com/29842841/38811170-32240752-4189-11e8-883c-45deee790871.PNG)

**Comment by Gebuz** [comment]
added in #1610
