### ISSUE TITLE
Trinket: Waycrest Manor: Lady Waycrest's Music Box

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1699]
![image](https://user-images.githubusercontent.com/4565223/40075398-7d92e8d4-587c-11e8-93bb-4e37db80bac0.png)
![image](https://user-images.githubusercontent.com/4565223/40075403-80001952-587c-11e8-8b05-96554c1dd5da.png)
![image](https://user-images.githubusercontent.com/4565223/40075410-824488d8-587c-11e8-8c3e-98449b35776b.png)

**Comment by Anatta336** [comment]
This trinket is now part of an interesting 2-part set with the ring Lord Waycrest's Signet:
http://bfa.wowhead.com/item=158362/lord-waycrests-signet

M+ log with the trinket and ring both equipped by a MW monk:
https://www.warcraftlogs.com/reports/hFdjJryNXxw7KCA9#fight=8&source=197

The damaging proc has ID 271671: http://bfa.wowhead.com/spell=271671/cacaphonous-chord
The healing proc has ID 271682: http://bfa.wowhead.com/spell=271682/harmonious-chord
I believe it's the same IDs regardless of having the set or not, but worth checking.

If you put the log into WoWAnalyzer and filter events by "chord" you can see there are plenty of times both chords activated at once, presumably from the set bonus. Generally you can tell which was the extra proc by seeing that it's unusually low (after accounting for crit, overheal/overkill, absorbs) compared to the other proc that it's paired with. Although that could break down if the player has a very powerful +heal or +damage (but not both) effect active on themselves when the procs happen.

If possible, it would be useful to calculate how much was gained from having the set bonus rather than just the trinket.

**Comment by sMteX** [comment]
Was already implemented https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/shared/modules/items/bfa/dungeons/LadyWaycrestsMusicBox.js
