### ISSUE TITLE
Refactor Analyzer: Reducer approach

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1802]
**This is a discussion issue, please talk to us before working on a solution.**

The approach of listening to events and analyzing chronologically comes from the time where we got events in batches of 300 and we were live-updating the interface. We've stopped doing that for a while (and it's been quite nice).

Another approach would be to have no event listeners at all and run a single reducer in the `on_finished`, `statistic` or `suggestions` methods. This approach has been discouraged so far since it would be inconsistent with the rest of the code base, but we should investigate if it may be cleaner, a viable alternative and if we should encourage this.

Listening to events is slow and may result in harder to test and uglier code. Reducers are generally pure which makes things easier to work with.

**Comment by emallson** [comment]
I'm very into this. Since reading this, I've been going through the brewmaster modules in my head wondering what would change. I believe it'd actually simplify much of my code because instead of doing this event fabrication stuff with `StaggerFabricator`, instead I could implement a reducer that produced the stagger pool contents as output that other reducers down the pipe consumed.

One of the big upsides I see from this is potential for improved testability. It's a huge pain to set up the web of dependencies a module needs to operate in a test environment, especially once you start having dependencies fabricating events. A stateless reducer-based system has potential to greatly simplify this.

I have found one current catch (in BrM), however: Guard. Guard requires operating on the stagger pool contents immediately or I'll get purify values wrong down the line. It is *probably* possible to write a normalizer for Guard that fixes the difficult-to-use way its logged, but it's something to consider.

I may mess with a reducer-based revamp of some of the core BrM modules to see if any other kinks arise that aren't just due to the mismatch in intent between the current `Analyzer` setup and reducers.

**Comment by MartijnHols** [comment]
Interactions like Guard are common across many specs and a reason to stick with the event based approach as those cases are usually simplified with that, and it may be easier to wrap your head around since it more closely matches in-game behavior. 

Normalizers are by themselves very complex and needing more due to this method would be bad. 

Maybe the question is whether it would be ok for some isolated modules to be implemented like this (e.g modules that don’t depend on core mechanics like stagger).

**Comment by MartijnHols** [comment]
I know a few people were excited about the prospect of this, but I don't think we should do this. It's not really viable for all analyzers and mixing things would be bad, especially when we'd eventually have to migrate modules made from reducer approach to the event based approach because a particular extra info is needed (similar to having to switch between React's functional components vs class based), but also because the reducer style would increase learning curve.

I think this means the reducer approach is going to be reason to reject PRs.

@emallson see the new TestCombatLogParser, this might help set up the web of dependencies. Feel free to make yourself a spec specific default with the modules you commonly need elsewhere enabled. This is the plan anyway once have the core separation implemented that I proposed on Discord. 

There's no shame testing multiple modules in a test, in fact it makes sure they're all interactions properly.

I wouldn't mind reconsidering.
