### ISSUE TITLE
Add a way to calculate fight downtime per boss

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1858]
- [ ] There must be a downtime specifically for damage dealing (e.g. for damaging abilities and abc)
- [ ] There must be a downtime specifically for healing (e.g. for healing abilities and heal time)
- [ ] There must be a downtime specifically for tanking (e.g. for defensive abilities)
- [ ] The way the downtime is calculated must be configurable per fight
- [x] The downtime must be exported as seconds
- [x] The downtime must be calculable from debuffs, buffs, player positioning or time dead

Gauging by these requirements I think the best implementation would be a per-boss fight module that tracks the downtime for each category and then makes it public for other modules.

**Comment by MartijnHols** [comment]
Changed from downtime to uptime since that's the part we're actually interested in, calling downtime would just be misdirection.

**Comment by MartijnHols** [comment]
An easy way to account for downtime in 90% of modules would be to account for it in the `fightDuration` property of the CombatLogParser. This has some challenges though:

- It works decently for short CDs, but long CDs continue running during the downtime. Should that be adjusted somehow?
- Healing/tanking/dps downtimes are different, so which one to use? How to account for different spells (e.g. a healer's healing spells vs a healer's dps spells).

**Comment by yajinni** [comment]
Hello
I noticed my demon hunter seems to be causing issues on argus. Will test other argus logs on from the DH. But this log i know is acting up:
https://wowanalyzer.com/report/vWgAk673Cm9ZVnDQ/9-Heroic+Argus+the+Unmaker+-+Kill+(8:54)/53-Deathnchaos

**Comment by Anatta336** [comment]
For the other 10% of modules it would be useful to have access to a combined downtime history (separate for heal/tank/dps I guess). So a module can find out if a specific time or period of time was downtime, whether due to death or boss mechanics.

At the moment `DeathDowntime` already provides this with `downtimeHistory`. Providing the same from boss downtime modules and combining them in `TotalDowntime` would be great.

I think downtime history would also be useful for #1863 

Example uses:
* A "your next cast in 10 seconds is free" proc should always get used. But if it occurs during downtime and expires before the downtime is over, failure to use it (probably) isn't a mistake.
* A rogue shouldn't let their energy hit the cap, but it capping during downtime isn't a problem. We'd get a moderately accurate result by subtracting total downtime from time capped. But it would be misleading if the player kept their energy uncapped during downtime and let it cap when they should have been fighting the boss.

**Comment by MartijnHols** [comment]
That's the idea, but it's a bit hard to implement correctly with just one downtime stat. Waiting for some WCL API changes that might land soon that will make it easier to add more bosses.
