### ISSUE TITLE
Subtlety Rogue: Add checklist

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2030]
The IV guide has a great list that can be used as basis: https://www.icy-veins.com/wow/subtlety-rogue-pve-dps-common-worst-mistakes

**Comment by TsaboTavok** [comment]
Hi Zero,

IcyVeins is viewed as a meme in the rogue community, so basing something on it is not a good idea in general. Also if you put the foot note in there, it will loose all credibility. 

In fact just this page of the guide has mistakes. For example: 
It is completely wrong to test if Shadow Dance was cast at 90+ energy, because the only thing that does matter is getting the maximum amount of casts during each dance.
Overcapping Combo Points is a huge mistake, but its not even mentioned .
His Nightblade example has only 1 case, that is not 100% correct. You can actually refresh Nightblade during Dance, if its outside of Symbols and you are not running DarkSahdow.

All of these things are handled by the current analysis. 

I have already started doing any new additions in the style required for checklist and will add it eventually (target is first raid week), so you can assign this issue to me. I will likely not have time to create checklists for Assassination and Outlaw in time tho, so help is more welcome in those specs =)

**Comment by MartijnHols** [comment]
M'kay. Going through the two guides, the IV version looks a lot more comprehensive and worked out than Wowhead's, which is very bare-bones. It's definitely not a *meme*, as they are working hard to provide quality guides for all specs.

1. Hitting max casts is impossible with energy though right? You can't really tell someone "get max casts in SD" as that really doesn't help them one bit achieving that. A guideline such as "try to be at 90 energy or more" is something that is very clear and doesn't require the player to figure it out for themselves. Maybe it should be less than 90 Energy, but I think it would be a nice requirement to get users in the right direction.
2. Sorry, I forgot about that. It should be in the first rule.
3. If the recommendation is to stack cooldowns, then shouldn't symbols be pretty much always up during SD?

I haven't touched Assassination nor Outlaw yet, so not prepared to do a checklist for those. I'll leave sub to you then.

**Comment by TsaboTavok** [comment]
Rogue theorycrafters put guides on http://www.ravenholdt.net/ or on discord pins. The IV rogue guides are a meme, because in the past they were always outdated and as a consequence wrong.

Regarding SD, its completely possible to get maximum amount of casts every dance, and the energy requirement for that depends on your talents. Under some conditions its actually impossible to run out of energy in Dance. I agree that the suggestion can hint at pooling energy.
