### ISSUE TITLE
"SOMETHING WENT WRONG TALKING TO WARCRAFT LOGS"

### ISSUE THREAD

**Issue by oBusk** [WoWAnalyzer/WoWAnalyzer#2124]
On: https://wowanalyzer.com/character/EU/Daggerspine/davai/

Get error:

> 500: <div class="content">  <script src="https://cdn.ravenjs.com/3.3.0/raven.min.js"></script> <script> Raven.showReportDialog({ eventId: '5b33cf9a0a914115b34f8403540177d7', // use the public DSN (dont include your secret!) dsn: 'https://e9ebbd88548a441288393c457ec90441@sentry.io/3235', user: { 'name': '', 'email': '', } }); </script> </div> Please message us on Discord or create an issue on Github if this issue persists and we will fix it, eventually.

**Comment by HawkCorrigan** [comment]
Warcraft logs is getting hammered today, so there are some faulty responses every so often.

Try turning on incognito-/private-mode in case an add on interferes with it and try again please.
It currently works on my end at least.

**Comment by joshinat0r** [comment]
Incognito isn't going to fix that :D

Kihra said about an hour ago that his azerite-code broke the API. The whole character-endpoint is gone and not returning JSON.

https://www.warcraftlogs.com/v1/parses/character/davai/Daggerspine/EU?api_key=c02be7c4f23394d13dfe1ed7036f4057

We can't do much about it except making a more obvious error-message.

**Comment by HawkCorrigan** [comment]
why the fuck did I get a proper response then 😕 
Makes more sense tho, if I think about the number of people reporting errors ^^

**Comment by joshinat0r** [comment]
The character endpoint is working again now, but it looks like the character has no logs, not even on WCLs website. Thought they appear instantly with an estimated percentile.

Either way, in the process of adding Uldir to the dropdown and making it the new default and it should work once WCLs is showing the reports ^^

**Comment by oBusk** [comment]
I don't have any logs in uldir I'm afraid! I was going to see if it could analyze mythic plus runs! It's not erroring anymore now! 👍

**Comment by joshinat0r** [comment]
Yeah, got fixed with #2125 .
Analyzing M+ is a moot point, it works but some metrics are off (like we display some buffs as 100%+ uptime (due to how fights are handled in a M+ log vs a raid log) and it's essentially shown as one big fight.

Adding them to the character's zone-dropdown might give the impression that the M+ analysis is working well enough and that might be misleading. I'll make sure to add them once we're confident enough to say that the M+ stuff is useful.

Anyways, will close this one since the bug is fixed.

And thanks for reporting the issue 👍
