### ISSUE TITLE
"An unknown error occured" when parsing specific report

### ISSUE THREAD

**Issue by oBusk** [WoWAnalyzer/WoWAnalyzer#2128]
When parsing https://www.warcraftlogs.com/reports/DXmVJKzL7RaB1Mw3 (Not in time Temple of Sethraliss M+2) (https://wowanalyzer.com/report/DXmVJKzL7RaB1Mw3) I get 

> An unknown error occured. 
> Corrupt Warcraft Logs API response received, this report can not be processed.

I tried to look at the API responses and the only thing i could spot was that the main report-fetching looks completely different from any working report.

> (bad) https://wowanalyzer.com/api/v1/report/fights/DXmVJKzL7RaB1Mw3?translate=true 
>
> vs.
>
> (working) https://wowanalyzer.com/api/v1/report/fights/2zqAtrWMbDVghG19?translate=true

* **PS.** I _know_ mythic+ is not fully supported. I just thought that failing hard is probably not wanted.

**Comment by joshinat0r** [comment]
We're aware of that issue. It looks like our caching API isn't working like it should when we receive a corrupted response once (got it probably in the first place because you tried loading it the first time when WCL had issues with Redis).

Can't give an ETA for a fix since Zero is the one that did the backend and he's busy right now.

**Comment by MartijnHols** [comment]
It should work now, please try again.

**Comment by oBusk** [comment]
@MartijnHols Seems to be working!

**Comment by joshinat0r** [comment]
Closing this one
