### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2403]
I implemented https://github.com/lingui/js-lingui/ and it seems to be working fine. A fair amount of work is still left to do such as:

- Localize spells automatically via the API and through custom ids so things like "Kick" don't interfere when we use that phrase elsewhere (spells should always 100% match in-game)
- Make it easy to contribute localizations via some interface (Crowdin? they're pretty expensive)
- Documentation
- Requiring all new PRs to be internationalized
- Automate extraction
- Hide languages with less than X% (10?) of the strings localized

But looking at other projects and their localization efforts, actually localizing things doesn't really seem that popular and I'd prefer a non-localized app than one that is mixed with English and local language. Is this really worth spending a lot of time on? **Please let us know if you want this and/or if you'd be willing to localize A LOT of things.** I'm going to put further effort on hold until it actually looks like people want this.

**Comment by Pewtro** [comment]
```Forcing all new PRs to be internationalized```
This seems overly demanding for all PRs?

**Comment by sMteX** [comment]
I don't know any languages besides Czech and English o.o

**Comment by dvdscripter** [comment]
@MartijnHols NICE!

Checking lingui docs you will need to extract and compile each time a new <Trans> is added? Better wrap it around some deploy routine because someone can forget these steps.

I opened the original issue because Brazilian community has limited access to resources to improve gameplay. Just yesterday I (Azralon) was which a group of Emerald Dream at Underrot +2, they had no idea what to do on spore/mushroom boss and this lead to 6 wipes and one member leaving midway. I explained the fight and remaining bosses just to end key. Leader said that he would not invite me because of the language but was happy to have it done.

I18n will not solve this problem but will create another resource where community can improve. So I support and will help where is possible. WoWAnalyzer and raidbots are pretty popular between mythic raider here in Brazil already.

Words like "WoWAnalyzer" might not need <Trans> tag. If we leave any entry on messages.json empty ("") they'll show in default (en) language?

**Comment by MartijnHols** [comment]
Thanks for sharing!

Right now yes, we will need to manually start the extraction. While this isn't such a big deal, I'll work on automating this at some point if the turns out to be a bottle neck or time consuming. It won't be required by PR contributors, but I'd do it fairly regularly until it's automated.

Indeed empty words should show up in the default language, though I recommend not relying on this and instead copying the phrase there. This will better reflect the language status and avoids any marking of non-translated strings we might do at some point.

**Comment by MartijnHols** [comment]
Closed in favor of #3803
