### ISSUE TITLE
[RFC] Storing/Showing Stat Info on Modules

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2436]
**Motivation**

Let's say you're pulling up the analyzer for the first time and you see that you mitigated 24% of hits with Shield of the Righteous on your prot paladin. How good is that? That stat is not something that is easy to look up on WCL, and we currently have no way of displaying it. It *is* possible to use WCL's built-in tools for finding highly-ranked or similar logs to get an idea (as I'm sure a few of us commonly do), but there are several extra steps to this.

What I'm proposing here is storing *distributional information* about logs that have been previously analyzed. By that I mean: when analyzing a new log, you can tell where it stands w.r.t. a stat (like hits mitigated with SotR) in comparison to all prior logs, but not necessarily get the complete list of previous stats.

**API Sketch**

I would like this to have as simple an API as possible, without overly restricting the kinds of things you can do with it. Something like this:

- `stats.quantile(key, x)` -- adds `x` to the distribution labeled `key` and then returns the quantile (aka percentile on WCL). the update of the distribution would be handled on the server-side given only the key and x.
- `stats.histogram(key, numBins)` -- returns the histogram data for the purposes of displaying a plot like the [binomial plots](https://user-images.githubusercontent.com/4909458/46378992-65694c00-c66b-11e8-983e-791be9a412fe.png) i have in a couple of modules.
- `stats.distributionInfo(key)` -- returns the information necessary to reconstruct the distribution (this info will ideally be very small; otherwise this call can't reasonably exist) the other calls would ideally be based on this

**Method**

Periodically collect the top N (~100) reports from WCL for a boss for each spec, and calculate statistics for these logs on the server and store them for later access. 

Currently, there is nothing that says a `statistic()` method has to return any kind of numeric data (though this is almost universally true). Frequently, the `value` field on a `StatisticBox` also has some additional information attached (like a unit, e.g. `100 DPS`). To deal with this (and to let a module store multiple stats where appropriate), we'd add another method: `storedStatistics() -> {key: statistic}`.

These objects would then be stored in a row in a table with a schema something like:

| Field Name | Description |
| --- | --- |
| module | Identifies the module to which the stat belongs. |
| key | statistic key, used by the module to identify it |
| statistic | the actual stat |

Then, since `N` is small, we can either efficiently answer quantile queries on the server side or relatively efficiently send the distribution info to the client to do things with.

**Potential Issues**

- This requires some means of server-side rendering, which we currently don't have access to.
- What do we do when there are very few logs on WCL for a spec on a fight?
- This overlaps with some of the tools that WCL provides. For example, we could also pull a highly-ranked report and the most similar report (maybe?) to compare against rather than storing our own stat info.

**Outcome**

What we'd end up with is the abillity to show, returning to my SotR example, that a user's 24% SotR mitigation was in the 40th (or 60th, or 80th) percentile, indicating that there was significant room for improvement. Similarly for many other stats. I'm sure there are other ways we could use this, but that is the *main contribution* I see right now.

**Conclusion**

While the specifics of storage/reconstruction might change, my goals for this are:

1. simple API for that allows quick prototyping
2. low storage footprint so that we can freely use stat info

Curious what you all think of the idea and of the issues I raised.

**Comment by MartijnHols** [comment]
How about making this a lot simpler by just showing the average for the top 100 reports? Aside from tanks (where I wouldn't know how to determine the top 100 reports), this could look like "you had 24% SotR mitigation (>=60% recommended - the top 100 players average 49%)". Would this not achieve a similar result while being much simpler to implement?

Most of this what you wrote goes over my head.

**Comment by emallson** [comment]
the issue with that would be processing each of the top 100 reports, but that could be done once and then cached for a period of time, so it would ultimately probably be way simpler in the long run

i got like halfway through writing this before i realized that approach would ultimately be simpler (as noted in the potential issues bit), though it isn't as cool :(

**Comment by MartijnHols** [comment]
We should be able to fetch that from WCL, and then just have a job running that analyzes them that periodically refreshes the top 100 list and imports new logs as they appear. Having 100 records per stat should be no big deal.

Another nice thing about grabbing the top 100 logs could be that we auto adjust suggestion thresholds based on real life things. This could help improve aoe vs st fights and stuff.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=64673848)](https://www.bountysource.com/issues/64673848-rfc-storing-showing-stat-info-on-modules)

**Comment by emallson** [comment]
Updated description from a method based on [this paper](https://arxiv.org/pdf/1803.01969.pdf) to a method as described by @MartijnHols.

I still would like the histogram/distributionInfo methods, but they get a lot less useful with this method since they only cover the top 100 rather than all logs.

**Comment by MartijnHols** [comment]
Related: #542

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=64673848)](https://www.bountysource.com/issues/64673848-rfc-storing-showing-stat-info-on-modules)

**Comment by Dambroda** [comment]
This is something I'd really like to implement before Shadowlands. The only problem I'm having right now is figuring out how to access the analyzers from the server.. everything else seems pretty easy. 

From what I've read here, it sounds like this is the general process that should be implemented:

1. Add a database table to store statistics for select modules. Pretty much simple key/value pairs. Maybe also a list of the reports that were used to grab the stats, so that we can skip over them and not waste processing time? Unless the module that generated the stat has been updated (see below)? Maybe include a bracket, so that users can analyze themselves against their own bracket rather than the overall top 100? Maybe include optional filters, so that stats for x module with y talent can be separate from stats for x module with z talent?
2. Add an method that modules can override to export their key and value. Maybe also a version, so that if the math is updated in an important way the database knows it has to regenerate statistics even if it analyzed a given report already.
3. Add a server api endpoint to query for said statistics from the database for given key (and bracket?), then implement the helper methods for that endpoint on the react client side so that maintainers can display it to the user
4. Create a job that populates the database with stats. On the server side, query WCL for the top 100  fights for a given boss for each spec (and optional filter?), and then process those fights through the specs analyzer. Processing through the analyzer is where I'm at a complete loss. In my line of work, this would be as simple as the WoWAnalyzer analyzers being a library I can reference from the server. Do we need to create a way to package up the analyzers for use on the server, and that package gets updated from the other github project? Is there an easier way that I'm missing? If I can get a point in the right direction here I think this addition is something I would really like to work on!

**Comment by MartijnHols** [comment]
Initial version can just have the frontend send the statistics to the server. While this could be manipulated, if that ever became an issue we can later implement a way to execute reports server-side to start validating results.

**Comment by Dambroda** [comment]
I think it's still very valuable to collect the top 100 reports versus the "top reports that people organically analyzed on WoWA". This being under the assumption that you meant "just send the statistics from the frontend when someone analyzes a fight". 

While it would be much easier to implement... I did have an idea to actually get the top 100 reports. Maybe it's completely ridiculous...

Create some sort of front end dashboard where we manage these statistics. Probably hidden, only maintainers/contributors need to see it? Maybe require github authentication? This dashboard lists all of the specs that have statistics exported, and all of the fights that need data. A person here can click a button to update statistics.

| Fight | Spec | Last Updated | By(github) | Update Now
| --- | --- | --- | --- | --- |
| Nzoth |
| | Frost Mage | Jun 10 | Dambroma | *CLICK*
| | Arcane Mage | Jun 10 | Vetsyt | *CLICK*
| | Fury Warrior | Jun 12 | Sharqq | *CLICK*
| | BMMonk | Jun 14 | emallson | *CLICK*
| Carapace |
| | Frost Mage | Jun 10 | Dambroma | *CLICK*
| | Arcane Mage | Jun 10 | Vetsyt | *CLICK*
| | Fury Warrior | Jun 12 | Sharqq | *CLICK*
| | BMMonk | Jun 14 | emallson | *CLICK*

etc..

The obvious problem with actually analyzing top 100's for a spec is that there are potentially 10+ fights in a tier, leading to 1000 WCL requests. I don't know what rate limits are right now, but we may even be able to, if needed, have the contributor/maintainer enter their API key on this page and it uses that for the update. 


If that's all ridiculous I can just work on the other option of exporting stats when a fight is analyzed

**Comment by MartijnHols** [comment]
Oh right. I think it should be possible to execute the app with a chromium browser on the CLI. That could then let the frontend store the data.

**Comment by MartijnHols** [comment]
> The obvious problem with actually analyzing top 100's for a spec is that there are potentially 10+ fights in a tier, leading to 1000 WCL requests. I don't know what rate limits are right now, but we may even be able to, if needed, have the contributor/maintainer enter their API key on this page and it uses that for the update.

I do not think we should mix API keys. I want all requests for main operations to be under the same key to be fair to WCL. 

This many calls should not be a problem outside peak. We could even spread it out over a day, week, month.

**Comment by ryanadean** [comment]
Adding some thoughts here, as in my work for Mobalytics.gg, I had some similar experience in API rate limits, update frequency, and the like. Take this with a grain of salt, what worked in league of legends and  what works in wow can and are very different things:

- Normalization of data: In league we normalized stats based upon your skill level, and that obviously would need to be done with the different dungeon levels (RF, norm, heroic, mythic). In addition, there are careful considerations we would make as to what other stats and metrics we would normalize against other values (in league, a great example is `by champion`. In wow, I think `ilvl` makes sense, and, depending, talent specs). For instance, uptime of a debuff that is affected by haste, for instance, would be impacted "generally" by ilvl (you could itemize terribly, which would and should reduce these values). But also, if you have a talent that extends the debuff duration (or something) you may want to normalize data accounting for that, so that you are able to assess how much are YOU actually doing the right thing as opposed to how much is your SPEC acting as a crutch.

This is a difficult process and there isn't a one-size-fits-all solution. But, there can be some pretty basic guidelines setup to help people out.

- Amount of data required / low-sample size combinations. I think the best approach is a two-prong attack on this: clear communication, and knowing when to "zoom out" a bit. In regards to clear communication, I think *both* an indication when someone is looking at numbers and there is a low sample size, some warning is important. Further, for transparency, indicating the sample size of data that is being used for the numbers that people are looking at allows for them to make judgement calls on how much stock to put into a percentile approach. Second, there are clear points, where normalizing by spec/ilvl/talent tree/legendary/whatever may result in a VERY small sample size, in which case the best thing to do is "zoom out" by removing some of the filters until a more reasonably sized set is found. This links back into clear communication of what and why this is happening.
- Data relevance - how long is data "good" for, until it becomes stale? As there are numbers tuning, and as people get better at mechanics or new strategies appear, older data becomes less relevant. I found that a simple decay function can go a long way.
- Data collection - None of this needs to be realtime. A rolling update worked best for us. You could get fancy and set up a system that makes API calls in a rate proportional to the number of requests on the site, but, a simple solution is probably just fine to start.


*ULTIMATELY though, I think the best approach on this is a simple one. Start by setting "thresholds" only. Use the top 100, the top 500 and top 2500, for instance as markers. Average the values around the point that you are looking at, maybe +/- 25-50. Store these. Test it out, see the value, then dig into more complex uses*

**Comment by MartijnHols** [comment]
Temporarily closing to shutdown BountySource
