### ISSUE TITLE
Cache character data

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#2471]
The Blizzard API is super slow and unstable, so we should cache character info in the character table. 

Consider making separate columns for extra fields like talents.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=64880822)](https://www.bountysource.com/issues/64880822-cache-character-data)

**Comment by hartra344** [comment]
@MartijnHols 
I'm working this issue. I have an initial pass at it working on my machine, however I have a few questions to make sure I'm taking the correct approach. 
I'm mostly a little curious as to how you see using this data in the future. 
Right now I'm doing it in such as way that I'm storing as little data as possible and it doesn't seem that the UI is currently using more than a couple of fields(race, selected spec in search profile, etc). 
Do you see the use of the API stretching farther than that? Do you think it'll need the full blob of talents(seems redundant since most of it is defined in the UI code)? how about other fields such as achievements, quests, stats, etc? Or will usage remain mostly as is(as far as you can see for now)?

What I am capturing now in my PoC I have working is role(it's used in Parses.js), selected spec, and selected talents(i.e. '1110200') which isn't used yet but seemed relevant.

**Comment by MartijnHols** [comment]
I looked at it recently and we do in fact use the talent response for something. I can’t remeber what though, but it was well hidden. 

In an ideal case we’d have a base char table with data stored semantically and a table for the other fields, storing as much data as possible as semantically as possible.

**Comment by MartijnHols** [comment]
Ah I see we just use role from the talent, so I guess that's enough. Great!
