### ISSUE TITLE
Test all combat log parsers 

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#2688]
Ensure every single spec _atleast_ actually compiles

**Comment by Dambroda** [comment]
Great idea. The only problem with this I can forsee would be people using incorrect values (based on bad math or existing code that doesn't work right) as their test criteria, which then fails when the code is fixed. Could lead to some confusion. We'd just need to be very anal about how people determine their test criteria as well

**Comment by emallson** [comment]
thats something i ran into with the old [brm test code.](https://github.com/WoWAnalyzer/WoWAnalyzer/blob/legion/src/Parser/Monk/Brewmaster/Modules/Core/BrewCDR.test.js) It broke several times in rapid succession because i set the test criteria based on bad values (which, tbf, the only values I had access to were the outputs from the analyzer because of the nature of that module).

so its something that will be a learning experience, but i think will be a valuable tool. especially since we have a lot of stable code now for handling CDR / buffs / whatever and for many things can cross-reference with WCL to double-check expected values

**Comment by MartijnHols** [comment]
This is here in the form of integration tests as used in specs such as Holy Paladin.
