### ISSUE TITLE
SotR Cooldown not calculated correctly (sometimes?)

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#2999]
https://wowanalyzer.com/report/86H1Jc29CRd7ajqD/28-Mythic+Opulence+-+Wipe+21+(8:37)/5-%D0%90%D0%B4%D0%BE%D1%80%D1%80%D1%8D

![screenshot from 2019-02-16 12-32-59](https://user-images.githubusercontent.com/4909458/52903101-01dd5680-31e7-11e9-81bd-c2af6ef94d34.png)
fight is 8 minutes long, should get way more than 5 casts.

Might be an opulence-related issue? Inspecting the cast efficiency shows it calculating the avg SotR cooldown as 25 (!) seconds. Base cooldown is 18s.

**Comment by yajinni** [comment]
the log you linked above seems to show the casts properly now. but per our discord discussion this log is showing issues.
https://wowanalyzer.com/report/4w3mvD9r7gNzXq8R/1-Normal+Champion+of+the+Light+-+Kill+(1:44)/Lovelycrits/statistics

Hawk thinks its due to maybe the it still waiting on the CD of it to finish once the fight is done.

**Comment by Sharrq** [comment]
With SOTR not having a CD in Shadowlands, this might not be relevant anymore? Since its now just a spender whenever you have holy power?

**Comment by emallson** [comment]
Nope, this can be closed.
