### ISSUE TITLE
Racials for Faction Swapped Encounters

### ISSUE THREAD

**Issue by Sharrq** [WoWAnalyzer/WoWAnalyzer#3014]
On fights where the player's faction gets swapped (Opulence, Conclave, Rastakhan for Horde and Mekkatorque, Blockade, Jaina for Alliance), the player's racials for their true race show as unused and the player gets dinged for it.

**Comment by MartijnHols** [comment]
I considered a solution for this a while ago, basically we could add a race conversion table to the possible boss config properties. Defaults to leaving it alone. It allows us to map races from old to new, e.g. Blood Elf -> Draenei, Draenei -> Draenei, Draenei -> Night Elf, etc. That way if Blizz ever decides to make a RP boss where certain races aren't allowed, we can account for that too (however unlikely this seems to be easy to support with this solution).

Also I was thinking about Alliance Trolls on Jaina since it was complaining about Berserking not being in the abilities.

**Comment by MartijnHols** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=70462156)](https://www.bountysource.com/issues/70462156-racials-for-faction-swapped-encounters)
