### ISSUE TITLE
Implement common haste trinkets in the Always Be Casting module

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#339]
Now that we can specify items with item level scaling in ABC we need to add the item buffs to make ABC for some specs more accurate.

Example:

https://wowanalyzer.com/report/vDwhbXMrWcmFG6kZ/26-Mythic+The+Desolate+Host+-+Kill+(7:19)/Pichan

Items:

- [ ] Whispers in the Dark - Hard: you will need to convert the casting speed to Haste for it to work properly, will require some theorycrafting.

**Comment by Iskalla** [comment]
After testing Whispers in the Dark i've arrived to the following conclusions:

- The buff works exactly the same as any other trinket that buffs haste (only the amount of haste is hugely higher)
- This means it can be implemented without problems unless haste module will be used to calculate haste-based CDs (this is the only situation where Whispers works different)
- The debuff works exactly the same as any other haste debuff
- The debuff is actually shown as a buff, and the event that raises is the buff one. This means that it'll probably need some sort of special code for it, since it has to go through _applyHasteLoss to work properly, instead of _applyHasteGain

I could easily implement the buff component of whispers, but i don't want to without having figured out how to do the debuff component first.
Any ideas?

**Comment by MartijnHols** [comment]
To be absolutely clear: You have confirmed its effect formula is `existingHaste * (1 + whispers casting speed) + whispers casting speed`? I'd have expected it to be `existingHaste * (1 + whispers casting speed)`

With regards to debuff, you could add a `hasteLoss` property next to https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e08c91b7e1bb53d6e560834f145a359aa21f15af/src/Parser/Core/Modules/Haste.js#L119 
Do leave a comment explaining why though, possibly linking this issue.

**Comment by Iskalla** [comment]
Ok, completely my fault, I was giving my numbers to other TCs yday and I believed their calculations.
I've re-done them myself today just to be sure, and you are right.

![image](https://user-images.githubusercontent.com/11649446/30880008-7dffb076-a301-11e7-87dc-b5efe4ba5747.png)
Marked in green the results that actually match my cast time for LS

So, to summarize
- The haste gain is calculated by `baseHaste * (1 + hasteGain)` and is shown as a buff
- The haste loss is calculated by `baseHaste / (1 + hasteLoss);` and is also shown as a buff


Since I was at it, i decided to test with ChronoShard, to see if for this one the current addHaste fx would work, but the haste ChronoShard gives is added as a raw stat gain before modifiers

![image](https://user-images.githubusercontent.com/11649446/30881169-2105dd1a-a305-11e7-8858-46732158ddf2.png)

In this case
- The haste gain is simply added to the current one


Maybe I'm not looking at the code properly, but I dont think this is reflected anywhere either.

Maybe we should add some sort of property to reflect if the haste gain of a trinket is Additive, Multiplicative or whatever Whispers is

**Comment by FaideWW** [comment]
Just curious - what is the reasoning behind https://github.com/WoWAnalyzer/WoWAnalyzer/blob/e08c91b7e1bb53d6e560834f145a359aa21f15af/src/Parser/Core/Modules/Haste.js#L196
being the formula for haste?  Shouldn't it be `existingHaste * (1 + hasteGain)`? Why the extra addition?

**Comment by MartijnHols** [comment]
That's just how the game does it, but I guess  🤷‍♂️

I suppose Haste procs that state a stat increase add to base Haste instead of are an increase to current Haste.

**Comment by MartijnHols** [comment]
Made an issue to track that separately.

**Comment by Iskalla** [comment]
Ok, my calculations where understanding baseHaste had the full component in (as in 1.28 base haste, not 0.28)

After quickly redoing them, `baseHaste * (1 + hasteGain) + hasteGain` is ok for both normal haste buffs and whispers buffs.

So we are back to first comment, whispers works as any other multiplicative buff, but we need to find a way to make the debuff act as haste loss.

Sorry for all the comments, but we were trying to wrap our heads around it for a while in druid discord xD

**Comment by FaideWW** [comment]
Ditto, it just occurred to me that `baseHaste` is the haste percentage, not the haste modifier.  Derp

**Comment by Gebuz** [comment]
handled by the stattracker module.
