### ISSUE TITLE
[Fury Warrior] Shadowlands Update

### ISSUE THREAD

**Issue by DylanDirlam** [WoWAnalyzer/WoWAnalyzer#3886]
Fury rotation remains mostly unchanged in prepatch and Shadowlands. 
### Talents
Make the following changes and verify that the module is still accurate for the talents:
* [ ] [New] Frenzy
* [ ] [New] Onslaught
* [ ] [New] Seethe
* [ ] [New] Cruelty
* [ ] Fresh Meat changes made
* [ ] Massacre changes made
* [ ] Dragon Roar changes made
* [ ] Frothing Berserker changes made
* [ ] Meat Cleaver changes made
* [ ] Reckless Abandon changes made
* [x] [Removed] Endless Rage
* [x] [Removed] Inner Rage
* [x] [Removed] Furious Slash
* [x] [Removed] Carnage

### Spells
* [x] Recklessness GCD removed
* [x] Rampage Coefficients changed

### Fury-Specific Legendaries
* [ ] [Cadence of Fujieda](https://shadowlands.wowhead.com/spell=335555/cadence-of-fujieda)
* [x] [Deathmaker](https://shadowlands.wowhead.com/spell=335567/deathmaker)
* [ ] [Reckless Defense](https://shadowlands.wowhead.com/spell=335582/reckless-defense)
* [ ] [Will of the Berserker](https://shadowlands.wowhead.com/spell=335594/will-of-the-berserker)

### Fury-Specific Conduits
* [ ] [Depths of Insanity](https://shadowlands.wowhead.com/spell=337162/depths-of-insanity)
* [ ] [Hack and Slash](https://shadowlands.wowhead.com/spell=337214/hack-and-slash)
* [ ] [Vicious Contempt](https://shadowlands.wowhead.com/spell=337302/vicious-contempt)
* [ ] [Ashen Juggernaut](https://shadowlands.wowhead.com/spell=335234/ashen-juggernaut)

### General
* [x] Delete azerite traits

**Comment by abelito75** [comment]
I know this is literally 2 years late and most of these won't make it into wowA but 
Thank you for the post. I have updated what was all completed on here.
I will note that since wowA is completely community driven we might not have someone with in depth knowledge of a spec. This means we need someone to be as specific as possible when requesting changes. So stating `Massacre changes` requires me to go down a rabbit hole to find what needs to be changed. Not trying to dissuade or undermine the post but rather make it so the next one is twice as good!
