### ISSUE TITLE
Prot Paladin: Track SotR uptime lost to overcapping

### ISSUE THREAD

**Issue by emallson** [WoWAnalyzer/WoWAnalyzer#3976]
requested by HoW staff

**Comment by hpabst** [comment]
I have a basic analyzer set up to track this by comparing the ideal buff uptime (4.5s of uptime per cast of SOTR) with the actual buff uptime. Do we know if the HoW staff want behavior any more complex than this? Pointing out 
which SOTR casts were overcaps, forgiving an overcap if they would start overcapping Holy Power otherwise, anything like that?

<img width="497" alt="2020-10-28 11_11_30-Heroic Wrathion - Kill (4_00) by Sêb in Ny'alotha - WoWAnalyzer" src="https://user-images.githubusercontent.com/6363390/97478761-9c73bf80-190e-11eb-9ff0-3f8eba46d777.png">

**Comment by emallson** [comment]
We should probably do the latter at a minimum, since there are only 2 HP
spenders and of the two SotR is the one that is generally better to press
"too much"
