### ISSUE TITLE
[SUGGESTIONS] Serrated Bone Spike

### ISSUE THREAD

**Issue by tyndivelspaz** [WoWAnalyzer/WoWAnalyzer#4231]
Use without overcapping Combo Points. Use on targets that don’t already have the debuff as long as they live for more than 5 seconds. Don't sit on 3 charges.

**Comment by soloxcx** [comment]
With the serrated bone spike (SBS) buffs, the rules for it changed quite a bit. Note that this is for outlaw rogue specifically. 

Single target - use SBS if it will get you to max cp exactly AND if opportunity or Skull and Crossbones are not active. Ignore this rule if overcapped or about to overcap 3 charges. 

Since SBS generates a fix amount of CP on single target and you are not punished for sitting on charges, it was found to be a gain to hold it for the moments where you need it most - where you have the worst builders available and if it will get you to max cp exactly.

AoE/cleave - Use on cooldown on different targets to generate cp. Essentially highest priority generator other than ambush but must be used on different targets and you still want to avoid overcapping combo points. If all targets have the bleed then you go back to single target logic. 

Source - I wrote the pinned message in the Ravenholdt outlaw channel after working with people testing out the changes
