### ISSUE TITLE
Broken contributor avatar links

### ISSUE THREAD

**Issue by DylanDirlam** [WoWAnalyzer/WoWAnalyzer#4441]
At some point recently the contributor avatars broke. This is on every page, not just limited to a single one.
![image](https://user-images.githubusercontent.com/5396389/111036541-a98cd900-83ed-11eb-9f92-f4a8ad474ccb.png)
![image](https://user-images.githubusercontent.com/5396389/111036545-ae518d00-83ed-11eb-9239-2ad20dd43586.png)

Viewing the image src shows: `src=[object Module]`.

**Comment by FlorianKem** [comment]
Could be related to some update to file-loader as suggested here: https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module
I looked at what the object contains, and indeed the string is not inside of .default


I tried to fix it by disabling the use of esModule like suggested there by adding following to the config-overrides.js
```(config) => {
    config.module.rules.push (
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              esModule: false,
            },
          },
        ],
      }
    )
    return config
  },
```
but that did not work for me. This could be related to me not properly setting it up.

What does resolve the problem is calling .default on the require() of the images like this in the CONTRIBUTORS.ts:
`  avatar: require('./interface/images/avatars/emallson-avatar.jpg').default,`

Sadly this again is disallowed by ESLint and it leads to the following error: `Require statement not part of import statement  @typescript-eslint/no-var-requires`
and I don't feel like disabling that error for the file by myself.

**Comment by DerAluDev** [comment]
Could be related to some update to file-loader as suggested here: https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module
I looked at what the object contains, and indeed the string is now inside of .default


I tried to fix it by disabling the use of esModule like suggested there by adding following to the config-overrides.js
```(config) => {
    config.module.rules.push (
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              esModule: false,
            },
          },
        ],
      }
    )
    return config
  },
```
but that did not work for me. This could be related to me not properly setting it up.

What does resolve the problem is calling .default on the require() of the images like this in the CONTRIBUTORS.ts:
`  avatar: require('./interface/images/avatars/emallson-avatar.jpg').default,`

Sadly this again is disallowed by ESLint and it leads to the following error: `Require statement not part of import statement  @typescript-eslint/no-var-requires`
and I don't feel like disabling that error for the file by myself.
