### ISSUE TITLE
[Suggestion] Support for translations (i18n)

### ISSUE THREAD

**Issue by dvdscripter** [WoWAnalyzer/WoWAnalyzer#45]
Hi, I would love to make translations for spells names but there is no option beside "name" at spells.

Any plan to implement this type of support?

**Comment by MartijnHols** [comment]
Adding support for localization is currently pretty low at the priority list. The focus at this time is making it as easy and clean as possible to add specs and features, and there are still some big steps to be done towards that goal.

**Comment by dvdscripter** [comment]
No problem, can I change name to named array? I known some js myself to try to implement it.

**Comment by MartijnHols** [comment]
I was hoping to solve all localization with https://github.com/yahoo/react-intl or a similar library, instead of building my own

**Comment by Yuyz0112** [comment]
@MartijnHols https://github.com/Automattic/i18n-calypso How about this project? I think it is lighter and easier to use.

**Comment by MartijnHols** [comment]
`react-intl` seems to have better JSX integration, which is important since this is a React project with most strings in React. Still, localization isn't a priority right now.

**Comment by Yuyz0112** [comment]
@MartijnHols ping

**Comment by MartijnHols** [comment]
You're welcome to.

I personally think it's more important to focus on expanding the tool with features that can help all users rather than localization for users that often can manage with English tools as well, and if not, probably going to have to get accustomed to it sooner or later. Localization costs a lot of time, is only relevant for a small subset of (potential) users and is not worth it if it comes at the cost of features that everyone can benefit from. Hence _low priority_.

**Comment by dvdscripter** [comment]
hm I think adding localization support early will cost less than adding later...

**Comment by MartijnHols** [comment]
Yes it probably is, but it's also easier to work on new features without having to worry about localization.

**Comment by MartijnHols** [comment]
I edited a couple of my messages to be less dismissive and *strongly worded*. Sorry if anyone took offense.

With the tool becoming largely feature complete and because I had to forcefully disable Google Translate because of [this bug](https://github.com/WoWAnalyzer/WoWAnalyzer/issues/948) it is becoming increasingly important to add localization. It is still a big undertaking.

I do want to make it clear that even if we do decide to implement this, our stance for new PRs will likely be that the localizable strings do not have to be localized prior to merging. Whether or not making them localizable will be a requirement remains to be discussed and depends on the complexity of doing so (react-intl is generally pretty complex, what I'm going to suggest below would be much easier). This will most definitely result in an app that is never 100% localized, but I still think that will be an improvement for users having difficulty understanding English.

I think https://webpack.js.org/plugins/i18n-webpack-plugin/ is worth considering as well. My opinion is that we should use what `create-react-app` is most likely to support by default.

**Comment by MartijnHols** [comment]
I'm currently thinking this module looks best:

https://github.com/lingui/js-lingui

**Comment by MartijnHols** [comment]
I might cancel this internationalization attempt. While I think I picked the right library, a fair amount of our code doesn't lend itself to internationalization yet (such as the checklist). Fixing these issues will take long too long and delay the release too long so that it might be better to just give up now and come back to it when the issues are fixed.

Another issue is that while it's the right library, it's not really mature. It misses namespacing and the it has different production behavior than development, leading to bugs like lack of translations in prod but not dev. And it doesn't do dynamic translations (like we do with our spells) well.

**Comment by MartijnHols** [comment]
I made a new issue to track this: https://github.com/WoWAnalyzer/WoWAnalyzer/issues/2403
