### ISSUE TITLE
Error statistics

### ISSUE THREAD

**Issue by nitzjr** [WoWAnalyzer/WoWAnalyzer#4816]
when trying to get the statistics (restoration shaman) after a few seconds it answers me with this error:

![image](https://user-images.githubusercontent.com/101800156/160565484-b9c20017-7440-4292-820d-6e9a2af313e5.png)

Error: Request timed out, probably due to an issue on our side. Try again.
    at https://wowanalyzer.com/static/js/main.a21570d9.js:2:359705
unhandledrejection

**Comment by abelito75** [comment]
Could you please link the log you're trying to use?

**Comment by nitzjr** [comment]
https://www.warcraftlogs.com/reports/VHgr2kZ1DLRAJ4Qt#fight=27&type=summary

**Comment by Enderah** [comment]
Hello ! 
I'm hijacking this ticket because it's something that seems similar; feel free to tell me if i should rather open a new one.

The shaman statistics now seems to sometimes load (same logs : my friend got the error screen nitzjr mentions. After an unusually long amount of time, it does load for me).

However next to the dps/hps meter the "percentile" part is empty as shown here -> https://i.imgur.com/yaBo8bQ.png 

Here is the report used : https://wowanalyzer.com/report/WLHvf2BXptrV9JZb

Thank you very much for your hard work ! <3 

Edit : i get the same result with other reports.

**Comment by emallson** [comment]
> However next to the dps/hps meter the "percentile" part is empty as shown here

This is a result of it being a Mythic+ log, which typically have few actual logs uploaded per key/key level.

However, I did figure out the issue that was causing the stats not to load. This should be fixed soon.

**Comment by Enderah** [comment]
Alright thank you ! It's surprising as all the other classes i've seen still have it (and shaman are not really rare in the content) but i guess it cant be helped.

Thank you for your work <3 

Edit : actually has been fixed now !

**Comment by abelito75** [comment]
This was fixed in #4829 closing
