### ISSUE TITLE
Add a module that tracks whether the player moved in the past x seconds

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#485]
Not really related to #399 as this would just track whether a player was moving recently (true or false). It might be desirable to reveal this for the past 1 second, 2 seconds, and 3 seconds.

**Comment by Gebuz** [comment]
I'm working on a module that tracks bad dot casts, and since dots are used as a movement filler for some specs it needs to check for recent movement when deciding if the cast is bad or not. Since the DistanceMoved module already has the last event with movement, you can simply compare that timestamp to see time since last movement. Returning the time since last movement is better than just a bool for recent movement imo, since the individual module can decide what it considers recent (in my case, I want to know if there was any movement since the dot cast).

It got me thinking if I should fabricate events for positionChanged. That would probably be the prettier version in terms of code but it would create a LOT of extra events, which probably isn't worth it considering how little movement is currently used.
