### ISSUE TITLE
Add Pantheon trinkets

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#486]
http://www.wowhead.com/news=272830/how-the-pantheon-trinkets-from-antorus-work

**Comment by sMteX** [comment]
Don't know if Wowhead updated the article (didn't read all), but previously it was that in order to activate the Pantheon bonus, the raid had to have **each** of the trinket procs *at the same time*. In recent patch build they changed that to be **4 trinket procs at the same time** (so now it's any 4 procs and Aman'Thul's Vision counts as any of those, like a wildcard). 

Source: http://www.wowhead.com/news=273700/argus-pantheon-trinket-updates-for-build-25255

**Comment by anom0ly** [comment]
Question - As we add more and more items, does it make sense to start building a folder structure to move common items into folders based on raid zones? Just to keep things cleaner?

**Comment by sMteX** [comment]
Perhaps so far it doesn't have to have a folder structure, just maybe split into separate files again and import and merge them in common/ITEMS/index.js. Imports from rest of the codebase stay intact and it can be divided however we like.

**Comment by MartijnHols** [comment]
I don't think the common/ITEMS directory needs splitting of files just yet, although it probably wouldn't hurt. As for the actual analyzers I think it would be great :D

**Comment by Pewtro** [comment]
Are these all added now?

**Comment by Gebuz** [comment]
closing since #1228 added the last missing trinket.
