### ISSUE TITLE
[Resto]  Add inefficient lifebloom/efflorescence usage checker.

### ISSUE THREAD

**Issue by buimichael** [WoWAnalyzer/WoWAnalyzer#649]
Check if a lifebloom/efflorescence has been cast within X seconds of last cast (i.e. ineffectily/refreshing them too early). Add this as a suggestion with the potential seconds/mana lost.

**Comment by pachonk** [comment]
Is there an example of "inefficient casts" in the system already?

**Comment by buimichael** [comment]
@pachok check the prematurerejuvenations.js

**Comment by buimichael** [comment]
Efflorescence is a little different though as you need to track all the recent casts and save the difference on cast. If it's > 30s

**Comment by pachonk** [comment]
Wrong mention, I'm @pachonk but I got the notification since I'm watching.
Thanks for the example! I'll take a look and see what I can find.

**Comment by mclifford82** [comment]
Hello, I have a version of a PrematureLifeblooms module working locally, however I have a few questions as this is my first module (and open source contribution in general).

![image](https://user-images.githubusercontent.com/853360/47946818-5544c680-dece-11e8-9fcb-2f02d92c8770.png)

![image](https://user-images.githubusercontent.com/853360/47946821-6988c380-dece-11e8-82b2-f3ffbfbf2538.png)

1. How do I only enable viewing the statsticbox when there are >0 premature Lifeblooms captured? I think the PrematureRejuvenations module works this way, but I couldn't pinpoint what was enabling that behavior.

2. Since early refreshes don't trigger the bloom proc, I thought it would be helpful to include information about how much healing is potentially lost. The way I thought to do it is to track each bloom proc's amount healed, average them out and get the product of that and the early refreshes. Regarding accuracy of metrics, I didn't know if that would be accurate enough to be useful. Thoughts?

3. Suggestion thresholds: `timeLostInSeconds, isGreaterThan: {   minor: 0,        average: 15,        major: 30,      },`
These are open for discussion. The majority of logs I reviewed at the Heroic level and above had druids with 2-4 early refreshes on longer encounters (if they had them at all; most Mythics did not), and the time lost varied between 1.2 seconds and 30 seconds. I also see quite a few examples of people with low total time lost, but a lot of early refreshes, meaning they refresh frequently with 1-3 seconds remaining until the pandemic timeframe and are also giving up a lot of potential bloom healing.

**Comment by buimichael** [comment]
@mclifford82 The premature rejuvenations modules does show even if there's 0 early refreshments. This is by design to show them if they did well essentially.  I'm wondering if it'd better to bake all three (rejuv, lb and efflo) into the same statisticsbox as it's similar information. To answer your question:

1. I think settings this.active = false will disable the module. Not sure if you can dynamically set this property on_finished for example.

2. Yes, that's fine.

3. Yes, lifebloom is a little different as the major loss of early refreshments comes from missing the bloom effect. We should probably factor in both the time lost (lb hot) and the potential lb bloom missed. We could instead calculate the % of all lb cast that were considered "bad LB usage" and give a suggestions based on that.

**Comment by pachonk** [comment]
Hmm, might be nice to add metadata for whether lifebloom is on a NEW target.
For instance, on a tank swap it's often a bad healing practice to leave lifebloom on the off target.

**Comment by abelito75** [comment]
Is there any progress on this still? As it is decently old and from talking to a some of the druid theorycrafters it doesn't seem to be all to important.

**Comment by MartijnHols** [comment]
Agreed
