### ISSUE TITLE
Cooldowns of abilities with stacks don't work properly in the timeline tab

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#793]
![image](https://user-images.githubusercontent.com/4565223/32698736-9c4c3608-c7aa-11e7-81bb-d763f4518cf5.png)

The correct behavior would be:
1. Show it on cooldown as long as at least 1 charge is recharging
2. Show it on cooldown when no charges are available

2 would be weird since then the first cast would show no cooldown. I think the best solution is to show both stacks with a opacity of like 33% so that the indicator gets darker when multiple stacks are on cooldown.

**Comment by kfinch** [comment]
Ok, I found the issue.

The timeline triggers drawing a cooldown bar on endcooldown, using the endcooldown event's 'begin' timestamp to mark the beginning. The problem is that for spells with charges, the 'begin' timestamp isn't when the cooldown started, it's instead when the spell last gained a charge.

**Comment by kfinch** [comment]
As a side note, my version of CastEfficiency that integrates SpellUsable does *not* suffer from this issue, as I noticed it during implementation and worked around it.
