### ISSUE TITLE
Adjust WCL Query to include Pre Pull Events

### ISSUE THREAD

**Issue by Sharrq** [WoWAnalyzer/WoWAnalyzer#806]
When looking at some Frost Mage Logs, and while getting feedback from the mage discord, we uncovered an issue where if you hit your cooldowns before the pull actually happens, or if you pre-cast Ebonbolt and the cast finishes before the pull happens (i.e. PreCast EbonBolt, Cast Finishes, Boss Pulls, Ebonbolt lands), then WowAnalyzer wont have any record of the cast and your cast efficiency will suffer.

For example
https://wowanalyzer.com/report/kT18gtvmGfaBLHQC/4-Heroic+The+Desolate+Host+-+Kill+(3:05)/Sharrq/timeline

If you look at the timeline, I had hit Icy Veins and Owl just barely before the pull but it didnt register. Therefore my cast efficiency for Owl is trashed (65%), and if Icy Veins' CD wasnt reduced then the cast efficiency of that would have been trash also (Its a 3 min cooldown that gets reduced every time Frostbolt crits).

Can the WCL Query Timestamps be adjusted to pull events 5-10 seconds before the pull? (that should cover the DKs that cast Army at -7 seconds ish, and i think Warlocks cast something earlyish also)

**Comment by Pewtro** [comment]
I think this is more so a fault of WCL not having the data, because it isn't logged in the combatlog?

**Comment by Sharrq** [comment]
As long as the player doesnt start logging as soon as the boss pulls, then it should be in there.

For example, I start logging as soon as i walk into the instance, so trash packs and such are all in the combat log .... the same should be true for everything cast during the prepull.

**Comment by MartijnHols** [comment]
I see you've closed the issue but I wanted to share my thoughts anyway in case the question/suggestion returns in the future, and since I feel I should have done that while it was still open.

There are a lot of factors that will make it unlikely and more importantly unreliable for there to be prepull events. Working on https://github.com/WoWAnalyzer/CombatLogParser I learned that the WCL uploader filters out trash fights by default, and I was planning on doing the same in our version. In addition I believe several addons are configured to only start pulling as combat starts, although these are likely to experience other issues as well.

I think it would be better if we accounted for this by looking at buff uptimes and damage events. We can assume that if a buff is present at pull that it was cast prepull and so increase the cast count, and a similar case can be made for damaging spells. Do you think this would solve this issue?

We could still decide that despite not *all* reports being enhanced the few that are might be worth fetch the prepull events, and we could do this, but this is a big challenge as we'll have to ensure it doesn't introduce errors anywhere else. I would not feel comfortable including prepull events by default and would make it an opt-in feature for modules to ensure this wouldn't introduce bugs.

Writing out these thoughts actually has me realizing it's not as challenging as I've been thinking from the moment you requested this as by making it an opt-in this we would introduce zero bugs while allowing modules to be enhanced as necessary. We could add another event filter, e.g. `on_prepull_byPlayer_cast` that could be listened to in the SpellUsable module. It would still leave some challenges though, such as not include the prepull time in the *time on cooldown* statistic.

If we are going to be doing this I'll have to take it into consideration in our own combat log parser so that it includes prepull data.

**Comment by Sharrq** [comment]
checking for buffs/debuffs and damage events was my plan to take care of this, I didnt realize that DBM and BigWigs started combat logging on pull ... I use Exorsus Raid Tools which starts logging when i walk into a raid instance and I just assumed they all worked this way. 

Ill probably open a separate issue for Prepull stuff in general. I was under the impression that this was as simple as telling the query to include a couple seconds before the pull, but I was mistaken. 

I thought about looking at this, but I ran into issues when i tried to think about how i could generalize it without having to provide a list of spells to look for on pull and how to hook it into cast effiiciency. 

Pretty much i need to figure out how to create a fabricated event to just add the cast at 0:00 and then problem solved
