### ISSUE TITLE
[Core] Add Scrollbar to Fight and Player Selectors

### ISSUE THREAD

**Issue by fasib** [WoWAnalyzer/WoWAnalyzer#824]
There is now way right now to select all the players/fights, if your window is to small.

![2017-11-18_09-31-02](https://user-images.githubusercontent.com/317216/32978483-515370c4-cc43-11e7-8ad6-dce8d702a5c3.gif)
^End of Browser

**Comment by Sinaloit** [comment]
This issue is still present even after the Grouping by Role change.  That change actually exacerbates the issue as there are now additional lines used up by the roles.  Zooming out your view will allow you to see more/all people but is not an optimal solution.  Collapsible roles groupings (Click on role) and maybe fight grouping (By sections listed in achievements?)  would work if a scroll enabled selector isn't feasible/ideal.

**Comment by MartijnHols** [comment]
This was fixed some time ago, thanks for the report!
