### ISSUE TITLE
[Vengeance] "Wasted" Soul Fragments

### ISSUE THREAD

**Issue by kaedys** [WoWAnalyzer/WoWAnalyzer#989]
The analyzer tracks and lists the number of "wasted" Soul Fragments (and recommends using Soul Cleave to consume them more often to avoid wasting them).  However, since [Patch 7.2.5](https://worldofwarcraft.com/en-us/news/20812012), exceeding the cap of 5 Soul Fragments automatically consumes the oldest fragments over the cap.  The only way to _waste_ fragments now is to be more than 60 yards from them when they would be consumed by this effect.

**Comment by ronaldpereira** [comment]
Hey @kaedys . Thanks for the feedback.

The "wasted" Soul Fragments on the Soul Fragments module is about how many SFs you haven't used in your rotation. So, if you consume the 6th SF by generating another one, that one enters as a wasted, because it hasn't affected any spell in the rotation (like Soul Bomb, that is empowered by how many SFs you consume when you use it).

**Comment by kaedys** [comment]
Hmm.  I'm on the fence on that.  I can understand counting them as a "wasted" resource, but the Fracture/Bomb build is kinda built around that.  The entire idea of that build is that you Bomb at 5 fragment for maximum DPS, or you generally sit at 5 fragments and just get the passive consumes on them as they spawn (giving better average Tormented uptime and trickle healing), and only Bomb often enough to refresh the debuff, if you absolutely need maximum survivability instead.  The former is generally the way most Veng DHs play, but the latter is still a solid strategy, and those fragments aren't "wasted" in such a playstyle.

**Comment by ronaldpereira** [comment]
I think this one here depends on your interpretation with "wasted". If you get it as "not consumed or even used", then you are totally right. But, I built this tracker to be a rotation and performance booster. So, the "wasted" Soul Fragments there is about not impacting into your rotation anywhere or even your DPS.

I know that many tanks has a different type of playing and it's own style. But I think it's kinda impossible to satisfy all of them. So I adopted the most used gameplay for it, that is an aggressive Vengeance DH tank (maximizing DPS).

Due to that, the "wasted" Soul Fragments is about not impacting into your DPS by getting into your rotation.

**Comment by kaedys** [comment]
Fair enough, I can accept that rationale.  I definitely interpreted it as "I didn't get the benefit of that soul fragment at all" when I saw it, though, so maybe a rephrase of that tracker?  Not really sure what a better name would be, though, so maybe not.

**Comment by ronaldpereira** [comment]
I've struggled on that name too when I was developing it. But I found "wasted" to be the most imparcial word to put in there. But if you think of a better name, I can totally overwrite it :)

**Comment by kaedys** [comment]
I was thinking `unused`, as it seems less...aggressive, I guess.  But even that's not technically accurate, even though it's has less of the "you literally lost something of value" feel to it.  `Underutilized` would probably be accurate, but it doesn't really roll off the tongue well, nor is it immediately obvious what is meant by it.  

Perhaps `unused` (or even `wasted`), but add a blurb to the mouseover box for it that indicates that these were simply Fragments that weren't used to empower other abilities.

**Comment by kaedys** [comment]
I dunno, it's a sticky one.  As they say, "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors."

**Comment by Gebuz** [comment]
now called "Inefficiently Used"
